name: cppcheck

on:
  push:
    branches:
      - master

jobs:
  upload-sarif:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Install Go and cppcheck-sarif
        run: |
          sudo apt-get update
          sudo apt-get install -y golang
          git clone https://github.com/Flast/cppcheck-sarif.git
          cd cppcheck-sarif
          go build -o /usr/local/bin/cppcheck-sarif .

      - name: Run cppcheck
        run: cppcheck --enable=all --xml --output-file=report.xml .

      - name: Generate SARIF file
        run: cppcheck-sarif -output report.sarif report.xml


      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif
          category: cppcheck
