name: cppcheck

on:
  [push, pull_request]

jobs:
  upload-sarif:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - run: |
          go build .
          sudo apt-get install -y cppcheck

      - run: |
          cppcheck --enable=all --xml --output-file=report.xml .
          cppcheck-sarif -output report.sarif report.xml

          cppcheck --errorlist > errorlist.xml
          cppcheck --xml --output-file=report.xml .
          cppcheck-sarif -errorlist errorlist.xml -output report.sarif report.xml

      - uses: Flast/cppcheck-sarif@v2
        with:
          input: report.xml
          output: report.sarif

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif
          category: cppcheck